In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('D:\\NOTES\\CSV FILES FOR ML\\Classification problems\\spam_emails.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
df.shape

(5572, 2)

In [6]:
df['Spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
df.drop('Category',axis='columns',inplace=True)
df.head()

Message  Spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1
3  U dun say so early hor... U c already then say...     0
4  Nah I don't think he goes to usf, he lives aro...     0

In [23]:
X = df.Message

In [24]:
y = df.Spam

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [26]:
X_train.shape

(4457,)

In [27]:
X_test.shape

(1115,)

In [28]:
y_train.shape

(4457,)

In [29]:
y_test.shape

(1115,)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


In [31]:
X_train_count = cv.fit_transform(X_train.values)

In [32]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(X_train_count,y_train)

MultinomialNB()

In [34]:
X_test_count = cv.transform(X_test)

In [35]:
mnb.score(X_test_count,y_test)

0.9883408071748879

In [36]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = cv.transform(emails)
mnb.predict(emails_count)

array([0, 1], dtype=int64)

# SKLEARN Pipeline

In [37]:
from sklearn.pipeline import Pipeline
clf = Pipeline([('vectorizer', CountVectorizer()),('nb', MultinomialNB())])

If we use sklearn.pipeline ,the we can directly fit our  model

In [39]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [40]:
clf.score(X_test,y_test)

0.9883408071748879

In [41]:
clf.predict(emails)

array([0, 1], dtype=int64)

our model ready now

In [42]:
import joblib as jb

In [43]:
jb.dump(clf,"Spam_emails_detection.pkl")

['Spam_emails_detection.pkl']

In [44]:
model = jb.load("Spam_emails_detection.pkl")

In [47]:
#Example : predict this email-- "Hey Winner!,How are you?"
model.predict(["Hey Brother,How are you?"])

array([0], dtype=int64)